// AUTOGENERATED by circuits/scripts/export-verifier.sh -- DO NOT EDIT.
// Regenerate:  cd circuits && CIRCUIT=ZcashPour npm run export-verifier
//
// circuit: ZcashPour.circom
// r1cs:    sha256:ca8c965d31282f3f974be9291a2d684b915f45b873229ea4233a4fb56bd062af
// zkey:    sha256:e7404d8ca8a392fcf0612dd458b9c4ba69cc02e736ce92ad1bea0bd949a6bf00
//
// SPDX-License-Identifier: GPL-3.0
/*
    Copyright 2021 0KIMS association.

    This file is generated with [snarkJS](https://github.com/iden3/snarkjs).

    snarkJS is a free software: you can redistribute it and/or modify it
    under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    snarkJS is distributed in the hope that it will be useful, but WITHOUT
    ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
    or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public
    License for more details.

    You should have received a copy of the GNU General Public License
    along with snarkJS. If not, see <https://www.gnu.org/licenses/>.
*/

pragma solidity >=0.7.0 <0.9.0;

contract ZcashPourVerifier {
    // Scalar field size
    uint256 constant r    = 21888242871839275222246405745257275088548364400416034343698204186575808495617;
    // Base field size
    uint256 constant q   = 21888242871839275222246405745257275088696311157297823662689037894645226208583;

    // Verification Key data
    uint256 constant alphax  = 3789108728854921112002253226211382590498593950286216856949856460351562314226;
    uint256 constant alphay  = 7913048880502585755748872840825623363930939220830242735613097306679523770962;
    uint256 constant betax1  = 21830407215017504078369416843689332040651383990978188515520195364221621009452;
    uint256 constant betax2  = 17071304700852496963298378207213012492709112385173498879756877047702785833847;
    uint256 constant betay1  = 3799332348415120166054978399977582282404284570012644432002609410999004869396;
    uint256 constant betay2  = 9737405635394212092194230156295386464602093813354573988359403022078675514538;
    uint256 constant gammax1 = 11559732032986387107991004021392285783925812861821192530917403151452391805634;
    uint256 constant gammax2 = 10857046999023057135944570762232829481370756359578518086990519993285655852781;
    uint256 constant gammay1 = 4082367875863433681332203403145435568316851327593401208105741076214120093531;
    uint256 constant gammay2 = 8495653923123431417604973247489272438418190587263600148770280649306958101930;
    uint256 constant deltax1 = 14077112896356285224834476325072765524247448147099095653343292963409558499312;
    uint256 constant deltax2 = 5036114832172324400826494467298313898915130036206526818993802146284597686860;
    uint256 constant deltay1 = 18278935695488543772953530437255897826690419028818818820356321509783254790611;
    uint256 constant deltay2 = 4992283747793803859303008943671641041394528678124077489001031135034394242145;

    
    uint256 constant IC0x = 4742376892556250330229416660195087476520569471896453758818543125718735549542;
    uint256 constant IC0y = 17099467133067431392725689163012811144490268773619355969006451583795213728653;
    
    uint256 constant IC1x = 5349325803748103098709697420832241624532891043743180508043763276364718854184;
    uint256 constant IC1y = 10987639774454211111740242285482970435585456036908577465035112091312084679901;
    
    uint256 constant IC2x = 20698664428832733816910067197209868980514353600503654273892305364909698452062;
    uint256 constant IC2y = 9646638958943253749781047380394817316240349638611866496558660178332601812291;
    
    uint256 constant IC3x = 2085691894625865776908993322163667208192392211455677510311235861828170122254;
    uint256 constant IC3y = 2411033076547760929925912355432819047344811249462621807052449907950140774413;
    
    uint256 constant IC4x = 9381618745270205836519717416352125103173195738012909505983468722745554460826;
    uint256 constant IC4y = 14212834444774172615448523519912138504875963265478560700323988391050836343001;
    
    uint256 constant IC5x = 10768917065052177788016000505024697906650762062227730324248189968889801321997;
    uint256 constant IC5y = 15042599593526936949232835018417080560600406481537796706138861465946288471243;
    
    uint256 constant IC6x = 12387341239359430545498316529270458121267231015385987931329985762123808762393;
    uint256 constant IC6y = 21795821069566448328023376929021509008083736822187516540677414742260348161449;
    
    uint256 constant IC7x = 9429212933085683727275905885669119109552454107119532265460020958906033196458;
    uint256 constant IC7y = 1964899641259271023037794203238037908015446810807673044109774557265874633489;
    
    uint256 constant IC8x = 10043862892723126174457674451560645052930863612681521122789320167601835001095;
    uint256 constant IC8y = 10701107932047978252701642863885446541266644438319497567997233774537921570223;
    
    uint256 constant IC9x = 17437479443881827305916868519075506015699958089763229581769998667931793934629;
    uint256 constant IC9y = 9766168142109982011865426964273328642883438824817529403160467058680270209442;
    
    uint256 constant IC10x = 4711459742776160290782981623831348165505468392742449404664683614712899310505;
    uint256 constant IC10y = 9472326222299642334892248392076196728265208465952217856302179317935344929344;
    
    uint256 constant IC11x = 12915573851484844600127611434953851473576025080506976771914294459277203736495;
    uint256 constant IC11y = 8464193657924172091932812834032335247570248967953486749733789753193659198713;
    
    uint256 constant IC12x = 2094193049231229600717365056129366114521848746622163270531585707298328066025;
    uint256 constant IC12y = 18962368939245711789990118036808456423452455572537582813314883712096874075275;
    
    uint256 constant IC13x = 3750675719158686317905701473146281373824611129281996676669192461864398731107;
    uint256 constant IC13y = 17261705439460632873625832780320052227566066654001364538152452346425661683697;
    
    uint256 constant IC14x = 6294762010253908808398693940636029294699735144387528194382568563258714840344;
    uint256 constant IC14y = 12577746356375252194875029355643790447785123983311542644989797657930960241670;
    
 
    // Memory data
    uint16 constant pVk = 0;
    uint16 constant pPairing = 128;

    uint16 constant pLastMem = 896;

    function verifyProof(uint[2] calldata _pA, uint[2][2] calldata _pB, uint[2] calldata _pC, uint[14] calldata _pubSignals) public view returns (bool) {
        assembly {
            function checkField(v) {
                if iszero(lt(v, r)) {
                    mstore(0, 0)
                    return(0, 0x20)
                }
            }
            
            // G1 function to multiply a G1 value(x,y) to value in an address
            function g1_mulAccC(pR, x, y, s) {
                let success
                let mIn := mload(0x40)
                mstore(mIn, x)
                mstore(add(mIn, 32), y)
                mstore(add(mIn, 64), s)

                success := staticcall(sub(gas(), 2000), 7, mIn, 96, mIn, 64)

                if iszero(success) {
                    mstore(0, 0)
                    return(0, 0x20)
                }

                mstore(add(mIn, 64), mload(pR))
                mstore(add(mIn, 96), mload(add(pR, 32)))

                success := staticcall(sub(gas(), 2000), 6, mIn, 128, pR, 64)

                if iszero(success) {
                    mstore(0, 0)
                    return(0, 0x20)
                }
            }

            function checkPairing(pA, pB, pC, pubSignals, pMem) -> isOk {
                let _pPairing := add(pMem, pPairing)
                let _pVk := add(pMem, pVk)

                mstore(_pVk, IC0x)
                mstore(add(_pVk, 32), IC0y)

                // Compute the linear combination vk_x
                
                g1_mulAccC(_pVk, IC1x, IC1y, calldataload(add(pubSignals, 0)))
                
                g1_mulAccC(_pVk, IC2x, IC2y, calldataload(add(pubSignals, 32)))
                
                g1_mulAccC(_pVk, IC3x, IC3y, calldataload(add(pubSignals, 64)))
                
                g1_mulAccC(_pVk, IC4x, IC4y, calldataload(add(pubSignals, 96)))
                
                g1_mulAccC(_pVk, IC5x, IC5y, calldataload(add(pubSignals, 128)))
                
                g1_mulAccC(_pVk, IC6x, IC6y, calldataload(add(pubSignals, 160)))
                
                g1_mulAccC(_pVk, IC7x, IC7y, calldataload(add(pubSignals, 192)))
                
                g1_mulAccC(_pVk, IC8x, IC8y, calldataload(add(pubSignals, 224)))
                
                g1_mulAccC(_pVk, IC9x, IC9y, calldataload(add(pubSignals, 256)))
                
                g1_mulAccC(_pVk, IC10x, IC10y, calldataload(add(pubSignals, 288)))
                
                g1_mulAccC(_pVk, IC11x, IC11y, calldataload(add(pubSignals, 320)))
                
                g1_mulAccC(_pVk, IC12x, IC12y, calldataload(add(pubSignals, 352)))
                
                g1_mulAccC(_pVk, IC13x, IC13y, calldataload(add(pubSignals, 384)))
                
                g1_mulAccC(_pVk, IC14x, IC14y, calldataload(add(pubSignals, 416)))
                

                // -A
                mstore(_pPairing, calldataload(pA))
                mstore(add(_pPairing, 32), mod(sub(q, calldataload(add(pA, 32))), q))

                // B
                mstore(add(_pPairing, 64), calldataload(pB))
                mstore(add(_pPairing, 96), calldataload(add(pB, 32)))
                mstore(add(_pPairing, 128), calldataload(add(pB, 64)))
                mstore(add(_pPairing, 160), calldataload(add(pB, 96)))

                // alpha1
                mstore(add(_pPairing, 192), alphax)
                mstore(add(_pPairing, 224), alphay)

                // beta2
                mstore(add(_pPairing, 256), betax1)
                mstore(add(_pPairing, 288), betax2)
                mstore(add(_pPairing, 320), betay1)
                mstore(add(_pPairing, 352), betay2)

                // vk_x
                mstore(add(_pPairing, 384), mload(add(pMem, pVk)))
                mstore(add(_pPairing, 416), mload(add(pMem, add(pVk, 32))))


                // gamma2
                mstore(add(_pPairing, 448), gammax1)
                mstore(add(_pPairing, 480), gammax2)
                mstore(add(_pPairing, 512), gammay1)
                mstore(add(_pPairing, 544), gammay2)

                // C
                mstore(add(_pPairing, 576), calldataload(pC))
                mstore(add(_pPairing, 608), calldataload(add(pC, 32)))

                // delta2
                mstore(add(_pPairing, 640), deltax1)
                mstore(add(_pPairing, 672), deltax2)
                mstore(add(_pPairing, 704), deltay1)
                mstore(add(_pPairing, 736), deltay2)


                let success := staticcall(sub(gas(), 2000), 8, _pPairing, 768, _pPairing, 0x20)

                isOk := and(success, mload(_pPairing))
            }

            let pMem := mload(0x40)
            mstore(0x40, add(pMem, pLastMem))

            // Validate that all evaluations ∈ F
            
            checkField(calldataload(add(_pubSignals, 0)))
            
            checkField(calldataload(add(_pubSignals, 32)))
            
            checkField(calldataload(add(_pubSignals, 64)))
            
            checkField(calldataload(add(_pubSignals, 96)))
            
            checkField(calldataload(add(_pubSignals, 128)))
            
            checkField(calldataload(add(_pubSignals, 160)))
            
            checkField(calldataload(add(_pubSignals, 192)))
            
            checkField(calldataload(add(_pubSignals, 224)))
            
            checkField(calldataload(add(_pubSignals, 256)))
            
            checkField(calldataload(add(_pubSignals, 288)))
            
            checkField(calldataload(add(_pubSignals, 320)))
            
            checkField(calldataload(add(_pubSignals, 352)))
            
            checkField(calldataload(add(_pubSignals, 384)))
            
            checkField(calldataload(add(_pubSignals, 416)))
            

            // Validate all evaluations
            let isValid := checkPairing(_pA, _pB, _pC, _pubSignals, pMem)

            mstore(0, isValid)
             return(0, 0x20)
         }
     }
 }
