// AUTOGENERATED by circuits/scripts/export-verifier.sh -- DO NOT EDIT.
// Regenerate:  cd circuits && CIRCUIT=ZcashPour npm run export-verifier
//
// circuit: ZcashPour.circom
// r1cs:    sha256:a69d1460e5cf606d3ae436069bb488869facb08f0dc1f3d169794401087b6b67
// zkey:    sha256:62f5c1c34848bffb523079540021dcf6ad8ec00dee6e4e193a7caeb0bc775457
//
// SPDX-License-Identifier: GPL-3.0
/*
    Copyright 2021 0KIMS association.

    This file is generated with [snarkJS](https://github.com/iden3/snarkjs).

    snarkJS is a free software: you can redistribute it and/or modify it
    under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    snarkJS is distributed in the hope that it will be useful, but WITHOUT
    ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
    or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public
    License for more details.

    You should have received a copy of the GNU General Public License
    along with snarkJS. If not, see <https://www.gnu.org/licenses/>.
*/

pragma solidity >=0.7.0 <0.9.0;

contract ZcashPourVerifier {
    // Scalar field size
    uint256 constant r    = 21888242871839275222246405745257275088548364400416034343698204186575808495617;
    // Base field size
    uint256 constant q   = 21888242871839275222246405745257275088696311157297823662689037894645226208583;

    // Verification Key data
    uint256 constant alphax  = 3789108728854921112002253226211382590498593950286216856949856460351562314226;
    uint256 constant alphay  = 7913048880502585755748872840825623363930939220830242735613097306679523770962;
    uint256 constant betax1  = 21830407215017504078369416843689332040651383990978188515520195364221621009452;
    uint256 constant betax2  = 17071304700852496963298378207213012492709112385173498879756877047702785833847;
    uint256 constant betay1  = 3799332348415120166054978399977582282404284570012644432002609410999004869396;
    uint256 constant betay2  = 9737405635394212092194230156295386464602093813354573988359403022078675514538;
    uint256 constant gammax1 = 11559732032986387107991004021392285783925812861821192530917403151452391805634;
    uint256 constant gammax2 = 10857046999023057135944570762232829481370756359578518086990519993285655852781;
    uint256 constant gammay1 = 4082367875863433681332203403145435568316851327593401208105741076214120093531;
    uint256 constant gammay2 = 8495653923123431417604973247489272438418190587263600148770280649306958101930;
    uint256 constant deltax1 = 9865553527576573708095108693837694857896010547735652680726625964195870760071;
    uint256 constant deltax2 = 10825150566638541709184157098986859751834350183543764252893415710749893058335;
    uint256 constant deltay1 = 6964119777067394887655850747540221692033519150541907182359423465268778816045;
    uint256 constant deltay2 = 14901548741954932228110225048089289686214790974226113432193485472379656674195;

    
    uint256 constant IC0x = 11248557148230007572509337887641779083936044357990652457715460354190140600457;
    uint256 constant IC0y = 10628353172495447155438366185735489191117047275027970551395650127740675619017;
    
    uint256 constant IC1x = 12963927084401513291195940046322071959286443479385380986566582116714146920863;
    uint256 constant IC1y = 7217451071101900485972927126471665940287016233835233924339614915822724741795;
    
    uint256 constant IC2x = 5431218371326605717605854289221958532988169518001128569691575824263863519878;
    uint256 constant IC2y = 13758289059148195012644481429336994686200548310399937686142879849621767180223;
    
    uint256 constant IC3x = 8170129447862771494559187931763167389327585990535493656828066140800858465271;
    uint256 constant IC3y = 3063855854807659654767356424604983493699974632346744282081464278340182200917;
    
    uint256 constant IC4x = 21261919127850998828188540709299796225156194904831683139791479250369956941167;
    uint256 constant IC4y = 6945730550970228062095389296475142170455110951429775292008051956483616863013;
    
    uint256 constant IC5x = 10876458339296097263221770131409151330153359815639130127342939907715149506326;
    uint256 constant IC5y = 19039531950735038013338248098841825069249037540162001729974863233722264228377;
    
    uint256 constant IC6x = 21058858955835884754784859847695084495482341898620986978859878717259918813328;
    uint256 constant IC6y = 21356308737969509107534543871575022284836761289154787566059180278421985323987;
    
    uint256 constant IC7x = 8255353219118961489581425500227065391199050089985001554058305278277383662193;
    uint256 constant IC7y = 6283229246033335328640372310031855086927584793737083646340610468743513043598;
    
    uint256 constant IC8x = 12822597749925495007020826769455903591492978232826652161391640300906712375436;
    uint256 constant IC8y = 18304727833181781433236131426133525523530752923639135136973653739310604651193;
    
    uint256 constant IC9x = 1494677036165977736161822117986830536226328055515697925435621176726098886187;
    uint256 constant IC9y = 3203980731928567934534654954638551529937359704912099031698456126238313595134;
    
    uint256 constant IC10x = 8925997864087199951341604632870929782288094605912875304987763703270329506708;
    uint256 constant IC10y = 11707406462574447293497213278240182466811656762311536615213264982027184630397;
    
    uint256 constant IC11x = 10785075435550765825085383321995176040519572326656306772420405572456101927704;
    uint256 constant IC11y = 16578692080593146193944005677591341437040641068634372907987618630576522938520;
    
    uint256 constant IC12x = 21436127352109846464892157641137174059952975527176150594959853405989817905250;
    uint256 constant IC12y = 18245214128904820494618605386049142701087396228459917824842582995732427119772;
    
    uint256 constant IC13x = 13746161906873026873041027088356774330051225985610947970402313908014487461667;
    uint256 constant IC13y = 372325933706014491944764407659751184932464165774392076562133372248044041968;
    
    uint256 constant IC14x = 1495819991395728423721557931222021396898119813400754562557943580711228436585;
    uint256 constant IC14y = 20386515544291830186318726815055674878116813832338186039368145319814969040667;
    
 
    // Memory data
    uint16 constant pVk = 0;
    uint16 constant pPairing = 128;

    uint16 constant pLastMem = 896;

    function verifyProof(uint[2] calldata _pA, uint[2][2] calldata _pB, uint[2] calldata _pC, uint[14] calldata _pubSignals) public view returns (bool) {
        assembly {
            function checkField(v) {
                if iszero(lt(v, r)) {
                    mstore(0, 0)
                    return(0, 0x20)
                }
            }
            
            // G1 function to multiply a G1 value(x,y) to value in an address
            function g1_mulAccC(pR, x, y, s) {
                let success
                let mIn := mload(0x40)
                mstore(mIn, x)
                mstore(add(mIn, 32), y)
                mstore(add(mIn, 64), s)

                success := staticcall(sub(gas(), 2000), 7, mIn, 96, mIn, 64)

                if iszero(success) {
                    mstore(0, 0)
                    return(0, 0x20)
                }

                mstore(add(mIn, 64), mload(pR))
                mstore(add(mIn, 96), mload(add(pR, 32)))

                success := staticcall(sub(gas(), 2000), 6, mIn, 128, pR, 64)

                if iszero(success) {
                    mstore(0, 0)
                    return(0, 0x20)
                }
            }

            function checkPairing(pA, pB, pC, pubSignals, pMem) -> isOk {
                let _pPairing := add(pMem, pPairing)
                let _pVk := add(pMem, pVk)

                mstore(_pVk, IC0x)
                mstore(add(_pVk, 32), IC0y)

                // Compute the linear combination vk_x
                
                g1_mulAccC(_pVk, IC1x, IC1y, calldataload(add(pubSignals, 0)))
                
                g1_mulAccC(_pVk, IC2x, IC2y, calldataload(add(pubSignals, 32)))
                
                g1_mulAccC(_pVk, IC3x, IC3y, calldataload(add(pubSignals, 64)))
                
                g1_mulAccC(_pVk, IC4x, IC4y, calldataload(add(pubSignals, 96)))
                
                g1_mulAccC(_pVk, IC5x, IC5y, calldataload(add(pubSignals, 128)))
                
                g1_mulAccC(_pVk, IC6x, IC6y, calldataload(add(pubSignals, 160)))
                
                g1_mulAccC(_pVk, IC7x, IC7y, calldataload(add(pubSignals, 192)))
                
                g1_mulAccC(_pVk, IC8x, IC8y, calldataload(add(pubSignals, 224)))
                
                g1_mulAccC(_pVk, IC9x, IC9y, calldataload(add(pubSignals, 256)))
                
                g1_mulAccC(_pVk, IC10x, IC10y, calldataload(add(pubSignals, 288)))
                
                g1_mulAccC(_pVk, IC11x, IC11y, calldataload(add(pubSignals, 320)))
                
                g1_mulAccC(_pVk, IC12x, IC12y, calldataload(add(pubSignals, 352)))
                
                g1_mulAccC(_pVk, IC13x, IC13y, calldataload(add(pubSignals, 384)))
                
                g1_mulAccC(_pVk, IC14x, IC14y, calldataload(add(pubSignals, 416)))
                

                // -A
                mstore(_pPairing, calldataload(pA))
                mstore(add(_pPairing, 32), mod(sub(q, calldataload(add(pA, 32))), q))

                // B
                mstore(add(_pPairing, 64), calldataload(pB))
                mstore(add(_pPairing, 96), calldataload(add(pB, 32)))
                mstore(add(_pPairing, 128), calldataload(add(pB, 64)))
                mstore(add(_pPairing, 160), calldataload(add(pB, 96)))

                // alpha1
                mstore(add(_pPairing, 192), alphax)
                mstore(add(_pPairing, 224), alphay)

                // beta2
                mstore(add(_pPairing, 256), betax1)
                mstore(add(_pPairing, 288), betax2)
                mstore(add(_pPairing, 320), betay1)
                mstore(add(_pPairing, 352), betay2)

                // vk_x
                mstore(add(_pPairing, 384), mload(add(pMem, pVk)))
                mstore(add(_pPairing, 416), mload(add(pMem, add(pVk, 32))))


                // gamma2
                mstore(add(_pPairing, 448), gammax1)
                mstore(add(_pPairing, 480), gammax2)
                mstore(add(_pPairing, 512), gammay1)
                mstore(add(_pPairing, 544), gammay2)

                // C
                mstore(add(_pPairing, 576), calldataload(pC))
                mstore(add(_pPairing, 608), calldataload(add(pC, 32)))

                // delta2
                mstore(add(_pPairing, 640), deltax1)
                mstore(add(_pPairing, 672), deltax2)
                mstore(add(_pPairing, 704), deltay1)
                mstore(add(_pPairing, 736), deltay2)


                let success := staticcall(sub(gas(), 2000), 8, _pPairing, 768, _pPairing, 0x20)

                isOk := and(success, mload(_pPairing))
            }

            let pMem := mload(0x40)
            mstore(0x40, add(pMem, pLastMem))

            // Validate that all evaluations ∈ F
            
            checkField(calldataload(add(_pubSignals, 0)))
            
            checkField(calldataload(add(_pubSignals, 32)))
            
            checkField(calldataload(add(_pubSignals, 64)))
            
            checkField(calldataload(add(_pubSignals, 96)))
            
            checkField(calldataload(add(_pubSignals, 128)))
            
            checkField(calldataload(add(_pubSignals, 160)))
            
            checkField(calldataload(add(_pubSignals, 192)))
            
            checkField(calldataload(add(_pubSignals, 224)))
            
            checkField(calldataload(add(_pubSignals, 256)))
            
            checkField(calldataload(add(_pubSignals, 288)))
            
            checkField(calldataload(add(_pubSignals, 320)))
            
            checkField(calldataload(add(_pubSignals, 352)))
            
            checkField(calldataload(add(_pubSignals, 384)))
            
            checkField(calldataload(add(_pubSignals, 416)))
            

            // Validate all evaluations
            let isValid := checkPairing(_pA, _pB, _pC, _pubSignals, pMem)

            mstore(0, isValid)
             return(0, 0x20)
         }
     }
 }
