#!/usr/bin/env bash
  #
  # Export the Solidity verifier into the hardhat project.
  #
  # The generated .sol is a build artifact, but it IS committed -- so the repo
  # compiles without anyone re-running the ceremony. Never edit it by hand.
  #
  #   npm run export-verifier
  #   CIRCUIT=pour npm run export-verifier
  #
  set -euo pipefail
  cd "$(dirname "$0")/.."
  
 CIRCUIT="${1:-${CIRCUIT:-Multiplier}}"
  BUILD="build/${CIRCUIT}"
  OUT_DIR="../contracts/contracts/verifiers"

  # Multiplier -> MultiplierVerifier, pour -> PourVerifier
  NAME="$(printf '%s' "${CIRCUIT:0:1}" | tr '[:lower:]' '[:upper:]')${CIRCUIT:1}Verifier"
  OUT="${OUT_DIR}/${NAME}.sol"

  sha256() {
    if command -v sha256sum >/dev/null 2>&1; then sha256sum "$1" | cut -d' ' -f1
    else shasum -a 256 "$1" | cut -d' ' -f1; fi
  }

  if [ ! -f "${BUILD}/${CIRCUIT}_final.zkey" ]; then
    echo "error: ${BUILD}/${CIRCUIT}_final.zkey not found -- run 'npm run setup' first" >&2
    exit 1
  fi

  mkdir -p "$OUT_DIR"

  echo "==> exporting solidity verifier"
  npx snarkjs zkey export solidityverifier \
    "${BUILD}/${CIRCUIT}_final.zkey" "${BUILD}/verifier.sol"

  # Banner carries no SPDX tag -- snarkjs already emits one further down, and two
  # would make solc complain.
  {
    echo "// AUTOGENERATED by circuits/scripts/export-verifier.sh -- DO NOT EDIT."
    echo "// Regenerate:  cd circuits && CIRCUIT=${CIRCUIT} npm run export-verifier"
    echo "//"
    echo "// circuit: ${CIRCUIT}.circom"
    echo "// r1cs:    sha256:$(sha256 "${BUILD}/${CIRCUIT}.r1cs")"
    echo "// zkey:    sha256:$(sha256 "${BUILD}/${CIRCUIT}_final.zkey")"
    echo "//"
    # snarkjs always names the contract Groth16Verifier; rename so several
    # verifiers can coexist in one hardhat project.
    sed "s/contract Groth16Verifier/contract ${NAME}/" "${BUILD}/verifier.sol"
  } > "$OUT"

  echo "wrote ${OUT}"
  echo "next: cd ../contracts && npx hardhat compile"